/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package com.ypg.dao.gae;


import com.google.appengine.api.datastore.DatastoreService;
import com.ypg.dao.BusinesDao;
import com.ypg.dao.DaoFactory;
import com.ypg.dao.PartnerDao;


/**
 * This is the main implementation class for obtaining DAO objects.
 * @author generated
 */
public class DaoFactoryImpl extends DaoFactory.Factory {
    public PartnerDao createPartnerDao( DatastoreService ds ) {
        return new PartnerDaoImpl( ds );
    }

    public BusinesDao createBusinesDao( DatastoreService ds ) {
        return new BusinesDaoImpl( ds );
    }

}
